version: '3'
services:

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  python-app:
    container_name: python-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    command: ["python", "main.py"]

volumes:
  qdrant_storage:
    # command: "uvicorn backend:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresql
    ports:
      - '5432:5432'
    volumes:
      - /data/postgresql_data:/var/lib/postgresql/data




